First attempt to create DocBook 5 MAIN
sknorr/dietrich pull request #11
Opened 2017-11-29 13:53 UTC by tomschr

* Add `chunker.xsl` from DocBook XSL
* Create `map-to-db5MAIN.xsl` to create DocBook5 output for MAIN file
* Implement previous stylesheet in `ditatodocbook.sh` script

2017-11-30 15:13 UTC, ghost requested changes
Just as a preliminary review for this.

2017-11-30 15:13 UTC, sknorr commented on map-to-db5MAIN.xsl
> +<?xml version="1.0"?>
Please just change the existing map-to-MAIN to work with DB5 instead. I don't see much use in converting to DocBook 4 when we can have 5. (I.e. I think Dietrich if can create DB5, there is no DB4 support needed.)

2017-11-30 15:13 UTC, sknorr commented on ditatodocbook.sh
> +[[ -e "$tmpdir/includes" ]] || die "ERROR: File $tmpdir/includes not found"
Use `-f` here -- I think `-e` would allow directories too

2017-11-30 15:13 UTC, sknorr commented on ditatodocbook.sh
> +MAP2MAIN_XSLT="$mydir/map-to-MAIN.xsl"
What is this good for? Especially among the "configurable" options, this seems misplaced.

2017-11-30 18:53 UTC, sknorr commented
I've had a look at the new `map-to-db5MAIN` file. 

* I diffed between `map-to-MAIN` and `map-to-db5MAIN`. Getting a 600-line diff for a 250-line file is ... unexpected. Most of the diffed lines are (unwanted) whitespace changes.
* Your reworking currently partially destroys the features to remove/replace files at the top level. To make this work properly, you would need to copy/paste the relevant parts of normal-mode templates into the collect.files templates.
* It is also incomplete, there is still an xsl:message for content that needs to go into `includes` at the end left.

This is all stuff that had already been working.

If this is just about seeing error and warning messages on the command line, it seems to me that there are easier ways to get those (like just outputting the message caught in includes after the xsltproc run).
That may not be proper-est way to go about this but it would be quick.

2017-12-01 08:57 UTC, tomschr commented on ditatodocbook.sh
> +MAP2MAIN_XSLT="$mydir/map-to-MAIN.xsl"
It's just my style. 😉  I don't want to repeat nor memorize the name of the stylesheet.

2017-12-01 08:58 UTC, tomschr commented on ditatodocbook.sh
> +[[ -e "$tmpdir/includes" ]] || die "ERROR: File $tmpdir/includes not found"
Yes, good idea! 👍

2017-12-01 09:43 UTC, sknorr commented on ditatodocbook.sh
> +MAP2MAIN_XSLT="$mydir/map-to-MAIN.xsl"
This is only used once. And it definitely should not be grouped together with the user-configurable options.

2017-12-01 13:18 UTC, sknorr commented on docbook/topic2db.xsl
> +      <xsl:when test="$contextType='article'">info</xsl:when>
I think this when is unnecessary now.

2017-12-04 18:48 UTC, sknorr commented
Hm, there still seem to be a few issues here that I didn't figure out:

* we're somehow writing the DB5 namespaces in lots of elements, not just the root element
* daps xmlformat does not run, the error is `ERROR: Failed to get filelist for ROOTID ""`

Also, I have moved your map/bookmap commit onto https://github.com/sknorr/dietrich/tree/f/map-to-bookmap

2017-12-21 10:08 UTC, merged